version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: card-service-db