server.port: 9091

spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15432/payment-service-db
    username: postgres
    password: password
  cloud:
    consul:
      host: localhost
      port: 8500
  config:
    import: optional:consul:localhost:8500
  flyway:
    baseline-on-migrate: true

resilience4j.retry:
    instances:
      walletService:
        max-attempts: 7
        exponential-backoff-multiplier: 1.5
        exponential-max-wait-duration: 5s
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - ea.slartibartfast.paymentservice.infrastructure.exception.WalletServiceNotAvailableException
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - ea.slartibartfast.paymentservice.domain.exception.BusinessException

slartibartfast.openapi.dev-url: http://localhost:9091