server.port: 9091
app:
  kafka:
    wallet:
      topic:
        default-name: wallet.balance-update
        retention: 7d
    card:
      topic:
        default-name: card.create
        retention: 7d
    deadletter:
      retention: 28d
      suffix: .DLT
    backoff:
      initial-interval: 500ms
      max-interval: 2s
      max-retries: 5
      multiplier: 1.5

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:19092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15432/payment-service-db
    username: postgres
    password: password
  cloud:
    consul:
      host: localhost
      port: 8500
  config:
    import: optional:consul:localhost:8500
  flyway:
    baseline-on-migrate: true

resilience4j.retry:
    retry-aspect-order: 2
    instances:
      walletService:
        max-attempts: 7
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 1.5
        exponential-max-wait-duration: 5s
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - ea.slartibartfast.paymentservice.infrastructure.exception.WalletServiceNotAvailableException
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - ea.slartibartfast.paymentservice.domain.exception.BusinessException
      cardService:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 1.5
        exponential-max-wait-duration: 5s
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - ea.slartibartfast.paymentservice.infrastructure.exception.CardServiceNotAvailableException
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - ea.slartibartfast.paymentservice.infrastructure.exception.CardNotFoundException
          - ea.slartibartfast.paymentservice.domain.exception.BusinessException

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      walletService:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        waitDurationInOpenState: 10000            #10 seconds
        minimumNumberOfCalls: 5                   #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - ea.slartibartfast.paymentservice.infrastructure.exception.BadRequestException
          - ea.slartibartfast.paymentservice.infrastructure.exception.AccountNotFoundException
        registerHealthIndicator: true

slartibartfast.openapi.dev-url: http://localhost:9091