server.port: 9093


spring:
  application:
    name: card-service
  cloud:
    consul:
      host: localhost
      port: 8500
  config:
    import: optional:consul:localhost:8500
  r2dbc:
    username: postgres
    password: password
    url: r2dbc:postgresql://localhost:35432/card-service-db
  flyway:
    url: jdbc:postgresql://localhost:35432/card-service-db
    baseline-on-migrate: true

slartibartfast.openapi.dev-url: http://localhost:9093
