server.port: 9093
app:
  kafka:
    topic:
      default-name: card.create
      retention: 7d
    deadletter:
      retention: 28d
      suffix: .DLT
    backoff:
      initial-interval: 500ms
      max-interval: 2s
      max-retries: 5
      multiplier: 1.5

spring:
  application:
    name: card-service
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: card-trx
      auto-offset-reset: latest
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:35432/card-service-db
    username: postgres
    password: password
  cloud:
    consul:
      host: localhost
      port: 8500
  config:
    import: optional:consul:localhost:8500
  flyway:
    baseline-on-migrate: true

slartibartfast.openapi.dev-url: http://localhost:9093
